serviceName: payment-service
namespace: production

image:
  repository: ghcr.io/udeeshajayendra/payment-service
  tag: latest

replicaCount: 3

ingress:
  enabled: true
  host: payment.production.local

hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 8

secret:
  DB_PASSWORD: changeme-production-password
